// Generated by CoffeeScript 1.9.3
(function() {
  var AreaEditor, areaEditObject, cssEditor, editors, htmlEditor, jsEditor;

  editors = document.getElementsByClassName('CodeMirror');

  AreaEditor = (function() {
    function AreaEditor(node) {
      this.node = node;
      this.node = this.node.CodeMirror;
    }

    AreaEditor.prototype.injectContent = function(content) {
      this.node.setValue(content);
      console.log(this.node);
      return this;
    };

    return AreaEditor;

  })();

  htmlEditor = new AreaEditor(editors[0]);

  cssEditor = new AreaEditor(editors[1]);

  jsEditor = new AreaEditor(editors[2]);

  areaEditObject = {
    AreaEditor: AreaEditor,
    htmlEditor: htmlEditor,
    cssEditor: cssEditor,
    jsEditor: jsEditor
  };

  window.AreaEditor = areaEditObject;

}).call(this);
