// Generated by CoffeeScript 1.9.3
(function() {
  var isConnected;

  isConnected = false;

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var socket;
    socket = new WebSocket("ws://127.0.0.1:8080");
    return socket.addEventListener("message", function(message) {
      if (!isConnected) {
        socket.send("test ws receive");
        isConnected = true;
      }
      return chrome.tabs.query({
        active: true,
        currentWindow: true
      }, function(tabs) {
        return chrome.tabs.sendMessage(tabs[0].id, {
          action: message.data
        }, function(response) {
          return console.log(response);
        });
      });
    });
  });

}).call(this);
