// Generated by CoffeeScript 1.9.3
(function() {
  var areaEdtiorJsUrl, handleStateChange, s, xhr;

  areaEdtiorJsUrl = chrome.extension.getURL('/scripts/AreaEditor.js');

  s = document.createElement("script");

  handleStateChange = function(c) {
    if (xhr.readyState !== 4) {
      return;
    }
    if (xhr.status !== 200) {
      return;
    }
    s.innerHTML = xhr.responseText;
    return document.body.appendChild(s);
  };

  xhr = new XMLHttpRequest();

  xhr.onreadystatechange = handleStateChange;

  xhr.open("GET", areaEdtiorJsUrl);

  xhr.send();

  chrome.runtime.sendMessage("connect", function(response) {
    return console.log(response);
  });

  chrome.extension.onMessage.addListener(function(msg, sender, sendResponse) {
    var content, data, functionToRun;
    if (msg.action !== "connected") {
      data = JSON.parse(msg.action);
    }
    s = document.createElement("script");
    if (data) {
      content = data.data.replace(/[\r\n]/g, "\\n");
      content = content.replace(/[']/g, "\\'");
      if (data.type === "html") {
        functionToRun = "AreaEditor.htmlEditor.injectContent('" + content + "')";
      }
      if (data.type === "css") {
        functionToRun = "AreaEditor.cssEditor.injectContent('" + content + "')";
      }
      if (data.type === "js") {
        functionToRun = "AreaEditor.jsEditor.injectContent('" + content + "')";
      }
      s.innerHTML = "(function() { " + functionToRun + " })();";
      return document.body.appendChild(s);
    }
  });

}).call(this);
